import { readFile } from "node:fs/promises";

import { aiCreditFor, commitSubject, safeSubject } from "./ai-credit";
import { parseCrawlProfile } from "./profile";

const testModuleName: string = "vitest";
const { describe, expect, it } = await import(testModuleName) as any;
const profile = parseCrawlProfile(JSON.parse(
  await readFile(new URL("../profiles/local-real-rounds.v2.json", import.meta.url), "utf8"),
));

describe("FR-034 AI-credit marker matching", () => {
  it("matches trailer lines with the configured key, tool name, optional version words, and service domain", () => {
    const credited = [
      ["Fix chat\n\nCo-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>", "GitHub Copilot"],
      ["Fix\r\n\r\nco-authored-by: Copilot App <1+Copilot@users.noreply.github.com>\r\n", "GitHub Copilot"],
      ["Fix\n\nCo-Authored-By: GitHub Copilot <bot@users.noreply.github.com>", "GitHub Copilot"],
      ["Refactor\n\nCo-Authored-By: Claude <noreply@anthropic.com>", "Claude"],
      ["Refactor\n\nCo-Authored-By: Claude Opus 4.1 <noreply@anthropic.com>", "Claude"],
      ["Refactor\n\nCo-Authored-By: Claude Sonnet 4.5 Thinking <noreply@ANTHROPIC.com>", "Claude"],
      ["Docs\n\nGenerated-by: Copilot", "GitHub Copilot"],
    ] as const;
    for (const [message, assistant] of credited) {
      expect(aiCreditFor(message, profile.aiCredits)).toEqual({ recorded: true, assistant });
    }
  });

  it("rejects near misses: other domains, people named like tools, extra words, bad spacing, and prose", () => {
    for (const message of [
      "Co-authored-by: Claude Monet <monet@example.org>",
      "Co-authored-by: Claudette <c@anthropic.com>",
      "Co-authored-by: Copilot <x@example.com>",
      "Co-authored-by: Claude One Two Three Four <noreply@anthropic.com>",
      "Co-authored-by:  Claude <noreply@anthropic.com>",
      "Co-authored-by: Claude <noreply@anthropic.com> extra",
      "Co-authored-by: Claude noreply@anthropic.com",
      "Co-authored-by: Claude <noreply@sub.anthropic.com.evil.test>",
      "Signed-off-by: Claude <noreply@anthropic.com>",
      "We asked Co-authored-by: Claude <noreply@anthropic.com> to help",
      "generated-by: Copilot",
      "Generated-by: Copilot please",
      "Refactor the Copilot integration",
    ]) {
      expect(aiCreditFor(message, profile.aiCredits)).toEqual({ recorded: false, assistant: null });
    }
  });

  it("reports the first credited assistant in message order", () => {
    const message = "x\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nCo-authored-by: Copilot <1+Copilot@users.noreply.github.com>";
    expect(aiCreditFor(message, profile.aiCredits)).toEqual({ recorded: true, assistant: "Claude" });
  });
});

describe("AI-deck commit subject screening", () => {
  it("takes the first line of the commit message as the subject", () => {
    expect(commitSubject("Fix flaky test\n\nBody text")).toBe("Fix flaky test");
    expect(commitSubject("Fix flaky test\r\nBody")).toBe("Fix flaky test");
  });

  it("accepts a short, identity-free subject", () => {
    expect(safeSubject("Fix off-by-one in pagination (#1968)", profile, { owner: "vercel", name: "next.js", authorName: "Ada", authorLogin: "ada" }))
      .toBe("Fix off-by-one in pagination (#1968)");
  });

  it("rejects long subjects, URLs, emails, handles, AI tool names, markers, and identities", () => {
    const identity = { owner: "vercel", name: "next.js", authorName: "Ada Lovelace", authorLogin: "ada" };
    for (const subject of [
      "x".repeat(101),
      "See https://example.test for details",
      "Thanks to a@example.org",
      "Address review from @octocat",
      "Copilot suggested this fix",
      "Use Claude to refactor",
      "Tweak GPT prompt handling",
      "Apply Codex output",
      "Cursor tab cleanup",
      "Gemini wiring",
      "aider: rename helper",
      "Co-authored-by: Claude",
      "Bump next.js runtime",
      "vercel: tidy logging",
      "Revert Ada Lovelace's change",
      "Revert ada's change",
      "Code generated by tool",
      "",
      "  padded  ",
    ]) {
      expect(safeSubject(subject, profile, identity)).toBeUndefined();
    }
  });
});
