import { languageExcerpt, looksGenerated } from "./excerpt-window";

const testModuleName: string = "vitest";
const { describe, expect, it } = await import(testModuleName) as any;
const limits = { maxLines: 20, maxBytes: 4096, minBytes: 64 };

describe("FR-023 experiment generated-file screen", () => {
  it("rejects files whose first thirty lines carry a generated marker, ignoring case", () => {
    for (const header of [
      "// This file was automatically generated and should not be edited.",
      "# Auto-generated by protoc",
      "/* @generated */",
      "// DO NOT EDIT",
      "// Code generated by mockgen. DO NOT EDIT.",
    ]) {
      expect(looksGenerated(`${header}\nconst x = 1;\n`, 30)).toBe(true);
    }
  });

  it("ignores markers after the scan window and ordinary prose", () => {
    const late = `${"const a = 1;\n".repeat(30)}// do not edit\n`;
    expect(looksGenerated(late, 30)).toBe(false);
    expect(looksGenerated("// Generates a report for editing later\nconst x = 1;\n", 30)).toBe(false);
  });
});

describe("FR-025 language excerpt window", () => {
  const body = (count: number, line = (index: number) => `value_${index} = compute(${index}) + offset`) =>
    Array.from({ length: count }, (_, index) => line(index)).join("\n");

  it("skips a shebang, licence comment block, blank lines, and a Python module docstring", () => {
    const source = [
      "#!/usr/bin/env python3",
      "# Copyright 2026 Example",
      "# Licensed under the Apache License, Version 2.0",
      "",
      '"""Module docstring that may mention the licence.',
      "More docstring text.",
      '"""',
      "",
      "import os",
      body(3),
    ].join("\n");
    const excerpt = languageExcerpt(source, "Python", limits)!;
    expect(excerpt.split("\n")[0]).toBe("import os");
    expect(excerpt).not.toMatch(/Licensed|Copyright|docstring|#!/u);
  });

  it("skips block and line comments for C-family languages, including a Rust inner doc", () => {
    const typescript = ["/* tslint:disable */", "/**", " * Licensed under MIT", " */", "// helper", "", "import { a } from './a';", body(3, (i) => `export const v${i} = a(${i}) + 1000;`)].join("\n");
    expect(languageExcerpt(typescript, "TypeScript", limits)!.split("\n")[0]).toBe("import { a } from './a';");
    const rust = ["//! Crate docs", "/// item docs", "use std::fmt;", body(3, (i) => `let v${i} = compute(${i}) + 1000;`)].join("\n");
    expect(languageExcerpt(rust, "Rust", limits)!.split("\n")[0]).toBe("use std::fmt;");
    const go = ["// Copyright 2026", "// SPDX-License-Identifier: MIT", "", "package main", body(3, (i) => `var v${i} = compute(${i}) + 1000`)].join("\n");
    expect(languageExcerpt(go, "Go", limits)!.split("\n")[0]).toBe("package main");
  });

  it("skips Ruby magic comments and =begin blocks", () => {
    const ruby = ["# frozen_string_literal: true", "=begin", "Licence text", "=end", "", "module Example", body(3, (i) => `  VALUE_${i} = compute(${i}) + 1000`)].join("\n");
    expect(languageExcerpt(ruby, "Ruby", limits)!.split("\n")[0]).toBe("module Example");
  });

  it("caps the window at twenty lines and 4,096 bytes on a line boundary and trims trailing blank lines", () => {
    const excerpt = languageExcerpt(`import os\n${body(40)}\n\n`, "Python", limits)!;
    expect(excerpt.split("\n")).toHaveLength(20);
    const wide = languageExcerpt(`import os\n${body(19, (i) => `x_${i} = "${"y".repeat(300)}"`)}`, "Python", limits)!;
    expect(Buffer.byteLength(wide)).toBeLessThanOrEqual(4096);
    expect(wide.endsWith('"')).toBe(true);
    expect(languageExcerpt("import os\nx = 1\n\n\n", "Python", { ...limits, minBytes: 1 })).toBe("import os\nx = 1");
  });

  it("returns undefined when too little code remains or nothing but comments exists", () => {
    expect(languageExcerpt("# only a comment\n\n", "Python", limits)).toBeUndefined();
    expect(languageExcerpt("x = 1\n", "Python", limits)).toBeUndefined();
    expect(languageExcerpt('"""never closed\nstill docstring\n', "Python", limits)).toBeUndefined();
  });
});
