import type { StackLanguage } from "./profile";

/** FR-023 as amended: experiment-local generated-file markers, matched case-insensitively. */
const GENERATED_MARKERS = /automatically generated|auto-generated|@generated|do not edit|code generated by/iu;

export const looksGenerated = (text: string, scanLines: number): boolean =>
  text.split(/\r?\n/u).slice(0, scanLines).some((line) => GENERATED_MARKERS.test(line));

export interface ExcerptLimits {
  readonly maxLines: number;
  readonly maxBytes: number;
  readonly minBytes: number;
}

const HASH_COMMENT_LANGUAGES = new Set<StackLanguage>(["Python", "Ruby"]);
const DOCSTRING_OPEN = /^[rRuUbBfF]{0,2}("""|''')/u;

/** Index of the first line that is code: not blank, not a comment, shebang, docstring, or licence header. */
const firstCodeLine = (lines: readonly string[], language: StackLanguage): number | undefined => {
  let index = 0;
  while (index < lines.length) {
    const line = lines[index]!.trim();
    if (line.length === 0 || (index === 0 && line.startsWith("#!"))) { index += 1; continue; }
    if (HASH_COMMENT_LANGUAGES.has(language)) {
      if (line.startsWith("#")) { index += 1; continue; }
      if (language === "Ruby" && line === "=begin") {
        const end = lines.findIndex((candidate, at) => at > index && candidate.trim() === "=end");
        if (end < 0) return undefined;
        index = end + 1; continue;
      }
      const docstring = language === "Python" ? DOCSTRING_OPEN.exec(line) : null;
      if (docstring) {
        const quote = docstring[1]!;
        const rest = line.slice(docstring[0].length);
        if (rest.includes(quote)) { index += 1; continue; }
        const end = lines.findIndex((candidate, at) => at > index && candidate.includes(quote));
        if (end < 0) return undefined;
        index = end + 1; continue;
      }
      return index;
    }
    if (line.startsWith("//")) { index += 1; continue; }
    if (line.startsWith("/*")) {
      const end = lines.findIndex((candidate, at) => at >= index && candidate.includes("*/", at === index ? line.indexOf("/*") + 2 : 0));
      if (end < 0) return undefined;
      const after = lines[end]!.slice(lines[end]!.indexOf("*/") + 2).trim();
      if (after.length > 0) return undefined;
      index = end + 1; continue;
    }
    return index;
  }
  return undefined;
};

/**
 * FR-025 as amended: the excerpt starts at the first code line, spans at most `maxLines` lines and
 * `maxBytes` bytes on a whole-line boundary, ends without trailing blank lines, and has at least
 * `minBytes` bytes. Returns undefined when no such excerpt exists.
 */
export const languageExcerpt = (
  text: string,
  language: StackLanguage,
  limits: ExcerptLimits,
): string | undefined => {
  const lines = text.replace(/\r\n?/gu, "\n").split("\n");
  const start = firstCodeLine(lines, language);
  if (start === undefined) return undefined;
  const window: string[] = [];
  let bytes = 0;
  for (const line of lines.slice(start, start + limits.maxLines)) {
    const added = Buffer.byteLength(line) + (window.length > 0 ? 1 : 0);
    if (bytes + added > limits.maxBytes) break;
    window.push(line);
    bytes += added;
  }
  while (window.length > 0 && window.at(-1)!.trim().length === 0) window.pop();
  const excerpt = window.join("\n");
  if (Buffer.byteLength(excerpt) < limits.minBytes || excerpt.trim().length === 0) return undefined;
  return excerpt;
};
